#!/usr/bin/perl -w
use strict;
use warnings;
use Telco::Info;
use Data::Printer;
use Getopt::Long;

my $tadig = undef;
my $imsi = undef;

GetOptions(
    'tadig|t=s' => \$tadig,
    'imsi|i=s'  => \$imsi
);

if(!defined($tadig) && !defined($imsi)){
    print <<EOF;

    Usage:
        telco-info -t=DOMCL -i=370010000000000
        telco-info --tadig=DOMCL --imsi=370010000000000

EOF

}

my $telco = Telco::Info->new();

if(defined($tadig)){
    print "############## Tadig ".$tadig." ##############\n";
    p $telco->findTelcoByTadig($tadig);
}

if(defined($imsi)){
    print "############## IMSI ".$imsi." ##############\n";
    p $telco->findTelcoByImsi($imsi);
}
